// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using v8desk.infrastructure.Persistence;

#nullable disable

namespace v8desk.infrastructure.Persistence.Migrations
{
    [DbContext(typeof(V8DeskDbContext))]
    [Migration("20261007095230_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("v8desk.domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<Guid?>("FilaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fila_destino_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("PaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("pai_id");

                    b.Property<bool>("PermiteChamadosComSubcategorias")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_chamados_com_subcategorias");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uuid")
                        .HasColumnName("setor_id");

                    b.Property<string>("VisibilidadePadrao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("visibilidade_padrao");

                    b.Property<string>("_preQualificacoes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pre_qualificacoes");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "FilaDestinoId");

                    b.HasIndex("EmpresaId", "PaiId");

                    b.HasIndex("EmpresaId", "SetorId", "PaiId", "Nome")
                        .IsUnique()
                        .HasFilter("ativa = TRUE");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EmpresaId", "SetorId", "PaiId", "Nome"), false);

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Chamado", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CategoriaAtual")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categoria_atual");

                    b.Property<string>("CicloVidaAplicado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ciclo_vida_aplicado");

                    b.Property<string>("ContextoAtual")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contexto_atual");

                    b.Property<string>("DescricaoOriginal")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("descricao_original");

                    b.Property<Guid>("FilaConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("fila_atual_id")
                        .HasComputedColumnSql("(contexto_atual -> 'Fila' ->> 'Id')::uuid", true);

                    b.Property<DateTimeOffset?>("LembreteValidacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lembrete_validacao_em");

                    b.Property<DateTimeOffset?>("LimiteReabertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("limite_reabertura");

                    b.Property<DateTimeOffset?>("LimiteValidacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("limite_validacao");

                    b.Property<string>("MetasSla")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metas_sla");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("prioridade");

                    b.Property<Guid?>("ResponsavelConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_atual_id")
                        .HasComputedColumnSql("(contexto_atual -> 'Responsavel' ->> 'Id')::uuid", true);

                    b.Property<Guid>("SetorConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("setor_atual_id")
                        .HasComputedColumnSql("(contexto_atual -> 'Setor' ->> 'Id')::uuid", true);

                    b.Property<Guid>("SetorOrigemConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("setor_origem_id")
                        .HasComputedColumnSql("(setor_origem_na_abertura ->> 'Id')::uuid", true);

                    b.Property<string>("SetorOrigemNaAbertura")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("setor_origem_na_abertura");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("visibilidade");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "SolicitanteId");

                    b.HasIndex("EmpresaId", "Status", "LimiteValidacao")
                        .HasFilter("status = 'Resolvido'");

                    b.HasIndex("EmpresaId", "FilaConsultaId", "Status", "AbertoEm", "Id")
                        .HasFilter("status NOT IN ('Encerrado', 'Cancelado', 'Resolvido')");

                    b.HasIndex("EmpresaId", "ResponsavelConsultaId", "Status", "AbertoEm", "Id");

                    b.ToTable("chamados", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.CicloAtendimento", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avaliacao")
                        .HasColumnType("jsonb")
                        .HasColumnName("avaliacao");

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrado_em");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<DateTimeOffset?>("LimiteAvaliacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("limite_avaliacao");

                    b.Property<string>("MotivoDeEncerramento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("motivo_de_encerramento");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Solucao")
                        .HasColumnType("jsonb")
                        .HasColumnName("solucao");

                    b.Property<string>("_solucoesRejeitadas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("solucoes_rejeitadas");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "ChamadoId", "Numero")
                        .IsUnique();

                    b.ToTable("ciclos_atendimento", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.CicloSla", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarioAplicado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calendario_aplicado");

                    b.Property<Guid?>("CicloAtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciclo_atendimento_id");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<decimal>("MetaAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("meta_aplicada");

                    b.Property<string>("MotivoFinalizacao")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("motivo_finalizacao");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uuid")
                        .HasColumnName("setor_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.Property<long>("VersaoPoliticaAplicada")
                        .HasColumnType("bigint")
                        .HasColumnName("versao_politica_aplicada");

                    b.Property<string>("_pausas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pausas");

                    b.Property<string>("_revisoesMeta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("revisoes_meta");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "CicloAtendimentoId", "Tipo")
                        .HasFilter("finalizado_em IS NULL");

                    b.HasIndex("EmpresaId", "SetorId", "Tipo", "IniciadoEm");

                    b.ToTable("ciclos_sla", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calendario")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calendario");

                    b.Property<int?>("LimiteSetoresPorAtendente")
                        .HasColumnType("integer")
                        .HasColumnName("limite_setores_por_atendente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PadraoCicloVida")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("padrao_ciclo_vida");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.EventoChamado", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Antes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("antes");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<string>("Depois")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("depois");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint")
                        .HasColumnName("sequencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "ChamadoId", "Sequencia")
                        .IsUnique();

                    b.ToTable("eventos_chamado", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Fila", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<bool>("Geral")
                        .HasColumnType("boolean")
                        .HasColumnName("geral");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("RegraAcessoRestrito")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("regra_acesso_restrito");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uuid")
                        .HasColumnName("setor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "SetorId", "Nome")
                        .IsUnique()
                        .HasFilter("ativa = TRUE");

                    b.ToTable("filas", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.MembroFila", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FilaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fila_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("AutorizadoParaRestritos")
                        .HasColumnType("boolean")
                        .HasColumnName("autorizado_para_restritos");

                    b.Property<Guid>("VinculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("vinculo_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "FilaId", "UsuarioId");

                    b.HasIndex("EmpresaId", "VinculoId");

                    b.ToTable("membros_fila", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("TextoOriginal")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("texto_original");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.Property<string>("_anexos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("anexos");

                    b.Property<string>("_correcoes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correcoes");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "ChamadoId", "CriadaEm", "Id");

                    b.ToTable("mensagens", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.PeriodoEtapa", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarioAplicado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calendario_aplicado");

                    b.Property<Guid?>("CicloAtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciclo_atendimento_id");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contexto");

                    b.Property<DateTimeOffset>("Entrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrada");

                    b.Property<Guid>("FilaConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("fila_atual_id")
                        .HasComputedColumnSql("(contexto -> 'Fila' ->> 'Id')::uuid", true);

                    b.Property<Guid?>("ResponsavelConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_atual_id")
                        .HasComputedColumnSql("(contexto -> 'Responsavel' ->> 'Id')::uuid", true);

                    b.Property<DateTimeOffset?>("Saida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saida");

                    b.Property<Guid>("SetorConsultaId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("setor_atual_id")
                        .HasComputedColumnSql("(contexto -> 'Setor' ->> 'Id')::uuid", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "CicloAtendimentoId")
                        .HasFilter("saida IS NULL");

                    b.HasIndex("EmpresaId", "SetorConsultaId", "Status", "Entrada");

                    b.ToTable("periodos_etapa", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.PoliticaSla", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PercentualAlerta")
                        .HasColumnType("numeric")
                        .HasColumnName("percentual_alerta");

                    b.Property<long>("Versao")
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.Property<string>("_metas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metas");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.ToTable("politicas_sla", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Setor", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CicloVidaEspecifico")
                        .HasColumnType("jsonb")
                        .HasColumnName("ciclo_vida_especifico");

                    b.Property<Guid>("FilaGeralId")
                        .HasColumnType("uuid")
                        .HasColumnName("fila_geral_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PoliticaSlaId")
                        .HasColumnType("uuid")
                        .HasColumnName("politica_sla_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "PoliticaSlaId");

                    b.ToTable("setores", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<bool>("DisponivelParaAtendimento")
                        .HasColumnType("boolean")
                        .HasColumnName("disponivel_para_atendimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.VinculoSetor", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uuid")
                        .HasColumnName("setor_id");

                    b.Property<Guid>("UsuarioPersistidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("_papeis")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("papeis");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "SetorId");

                    b.HasIndex("EmpresaId", "UsuarioPersistidoId", "SetorId")
                        .IsUnique()
                        .HasFilter("ativo = TRUE");

                    b.ToTable("vinculos_setor", (string)null);
                });

            modelBuilder.Entity("v8desk.infrastructure.Persistence.OutboxMensagem", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processada_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "CriadaEm", "Id")
                        .HasFilter("processada_em IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("v8desk.domain.Entities.Categoria", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Fila", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "FilaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("v8desk.domain.Entities.Categoria", "Pai")
                        .WithMany("Subcategorias")
                        .HasForeignKey("EmpresaId", "PaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("v8desk.domain.Entities.Setor", null)
                        .WithMany("Categorias")
                        .HasForeignKey("EmpresaId", "SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Chamado", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.CicloAtendimento", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Chamado", null)
                        .WithMany("Ciclos")
                        .HasForeignKey("EmpresaId", "ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("v8desk.domain.Entities.CicloSla", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.CicloAtendimento", null)
                        .WithMany("CiclosSla")
                        .HasForeignKey("EmpresaId", "CicloAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("v8desk.domain.Entities.EventoChamado", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Chamado", null)
                        .WithMany("Eventos")
                        .HasForeignKey("EmpresaId", "ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.Fila", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Setor", null)
                        .WithMany("Filas")
                        .HasForeignKey("EmpresaId", "SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.MembroFila", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Fila", null)
                        .WithMany("Membros")
                        .HasForeignKey("EmpresaId", "FilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.VinculoSetor", "Vinculo")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "VinculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vinculo");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Mensagem", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Chamado", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("EmpresaId", "ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("v8desk.domain.Entities.PeriodoEtapa", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.CicloAtendimento", null)
                        .WithMany("Periodos")
                        .HasForeignKey("EmpresaId", "CicloAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("v8desk.domain.Entities.PoliticaSla", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.Setor", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.PoliticaSla", "Sla")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "PoliticaSlaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sla");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Usuario", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.VinculoSetor", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Setor", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("v8desk.domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "UsuarioPersistidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("v8desk.infrastructure.Persistence.OutboxMensagem", b =>
                {
                    b.HasOne("v8desk.domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("v8desk.domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Chamado", b =>
                {
                    b.Navigation("Ciclos");

                    b.Navigation("Eventos");

                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("v8desk.domain.Entities.CicloAtendimento", b =>
                {
                    b.Navigation("CiclosSla");

                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Fila", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("v8desk.domain.Entities.Setor", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Filas");
                });
#pragma warning restore 612, 618
        }
    }
}
